nodes:
    # Virtual Control Plane nodes

    ctl01.physical-mcp10-dvr.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - openstack_control_leader
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl

    ctl02.physical-mcp10-dvr.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - openstack_control
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl

    ctl03.physical-mcp10-dvr.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - openstack_control
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl

    dbs01.physical-mcp10-dvr.local:
      reclass_storage_name: openstack_database_node01
      roles:
      - openstack_database_leader
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl

    dbs02.physical-mcp10-dvr.local:
      reclass_storage_name: openstack_database_node02
      roles:
      - openstack_database
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl

    dbs03.physical-mcp10-dvr.local:
      reclass_storage_name: openstack_database_node03
      roles:
      - openstack_database
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl

    msg01.physical-mcp10-dvr.local:
      reclass_storage_name: openstack_message_queue_node01
      roles:
      - openstack_message_queue
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl

    msg02.physical-mcp10-dvr.local:
      reclass_storage_name: openstack_message_queue_node02
      roles:
      - openstack_message_queue
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl

    msg03.physical-mcp10-dvr.local:
      reclass_storage_name: openstack_message_queue_node03
      roles:
      - openstack_message_queue
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl

    mdb01.physical-mcp10-dvr.local:
      reclass_storage_name: openstack_telemetry_node01
      roles:
      - openstack_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    mdb02.physical-mcp10-dvr.local:
      reclass_storage_name: openstack_telemetry_node02
      roles:
      - openstack_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    mdb03.physical-mcp10-dvr.local:
      reclass_storage_name: openstack_telemetry_node03
      roles:
      - openstack_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    mon01.physical-mcp10-dvr.local:
      reclass_storage_name: stacklight_server_node01
      roles:
      - stacklightv2_server_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    mon02.physical-mcp10-dvr.local:
      reclass_storage_name: stacklight_server_node02
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    mon03.physical-mcp10-dvr.local:
      reclass_storage_name: stacklight_server_node03
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    mtr01.physical-mcp10-dvr.local:
      reclass_storage_name: stacklight_telemetry_node01
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    mtr02.physical-mcp10-dvr.local:
      reclass_storage_name: stacklight_telemetry_node02
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    mtr03.physical-mcp10-dvr.local:
      reclass_storage_name: stacklight_telemetry_node03
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    log01.physical-mcp10-dvr.local:
      reclass_storage_name: stacklight_log_node01
      roles:
      - stacklight_log_leader_v2
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    log02.physical-mcp10-dvr.local:
      reclass_storage_name: stacklight_log_node02
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    log03.physical-mcp10-dvr.local:
      reclass_storage_name: stacklight_log_node03
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    prx01.physical-mcp10-dvr.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl

#    bmk01.physical-mcp10-dvr.local:
#      reclass_storage_name: openstack_benchmark_node01
#      roles:
#      - openstack_benchmark
#      interfaces:
#        ens3:
#          role: single_ctl
