nodes:
    cfg01.cookied-bm-dpdk-pipeline.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_static_ctl

    # Physical nodes
    kvm01.cookied-bm-dpdk-pipeline.local:
      reclass_storage_name: infra_kvm_node01
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp3s0f0:
          role: single_mgm
        enp3s0f1:
          role: bond0_ab_ovs_vlan_ctl

    kvm02.cookied-bm-dpdk-pipeline.local:
      reclass_storage_name: infra_kvm_node02
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp3s0f0:
          role: single_mgm
        enp3s0f1:
          role: bond0_ab_ovs_vlan_ctl

    kvm03.cookied-bm-dpdk-pipeline.local:
      reclass_storage_name: infra_kvm_node03
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp3s0f0:
          role: single_mgm
        enp3s0f1:
          role: bond0_ab_ovs_vlan_ctl

    cmp001.cookied-bm-dpdk-pipeline.local:
      reclass_storage_name: openstack_compute_node01
      roles:
      - openstack_compute_dpdk
      - features_lvm_backend
      - linux_system_codename_xenial
      - openstack_compute_sriov
      interfaces:
        enp5s0f0:
          role: combined_vlan_ctl_mgm
        enp3s0f0:
          role: bond_dpdk_prv_lacp
          dpdk_pci: "0000:03:00.0"
        enp3s0f1:
          role: bond_dpdk_prv_lacp
          dpdk_pci: "0000:03:00.1"

    cmp002.cookied-bm-dpdk-pipeline.local:
      reclass_storage_name: openstack_compute_node02
      roles:
      - openstack_compute_dpdk
      - features_lvm_backend
      - linux_system_codename_xenial
      - openstack_compute_sriov
      interfaces:
        enp5s0f0:
          role: combined_vlan_ctl_mgm
          single_address: 10.167.11.106
        enp3s0f0:
          role: bond_dpdk_prv_lacp
          dpdk_pci: "0000:03:00.0"
          tenant_address: 10.167.12.106
        enp3s0f1:
          role: bond_dpdk_prv_lacp
          dpdk_pci: "0000:03:00.1"

    gtw01.cookied-bm-dpdk-pipeline.local:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        enp3s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_dvr_vxlan_ctl_mesh_external
          external_address: 172.17.42.134
          external_network_netmask: 255.255.255.192

    gtw02.cookied-bm-dpdk-pipeline.local:
      reclass_storage_name: openstack_gateway_node02
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        enp3s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_dvr_vxlan_ctl_mesh_external
          external_address: 172.17.42.135
          external_network_netmask: 255.255.255.192
