nodes:
    cfg01.mcp-pike-dvr-ssl.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl01.mcp-pike-dvr-ssl.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - infra_kvm
      - openstack_control_leader
      - openstack_database_leader
      - openstack_message_queue
      - features_lvm_backend_control
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl02.mcp-pike-dvr-ssl.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - infra_kvm
      - openstack_control
      - openstack_database
      - openstack_message_queue
      - features_lvm_backend_control
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl03.mcp-pike-dvr-ssl.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - infra_kvm
      - openstack_control
      - openstack_database
      - openstack_message_queue
      - features_lvm_backend_control
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    kmn01.mcp-pike-dvr-ssl.local:
      reclass_storage_name: openstack_barbican_node01
      roles:
      - openstack_barbican
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    kmn02.mcp-pike-dvr-ssl.local:
      reclass_storage_name: openstack_barbican_node02
      roles:
      - openstack_barbican
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    kmn03.mcp-pike-dvr-ssl.local:
      reclass_storage_name: openstack_barbican_node03
      roles:
      - openstack_barbican
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    prx01.mcp-pike-dvr-ssl.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    # Generator-based computes. For compatibility only
    cmp<<count>>.mcp-pike-dvr-ssl.local:
      reclass_storage_name: openstack_compute_rack01
      roles:
      - openstack_compute
      - features_lvm_backend_volume_vdb
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: bond0_ab_ovs_vxlan_mesh
        ens6:
          role: bond1_ab_ovs_floating

    gtw01.mcp-pike-dvr-ssl.local:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      classes:
      - system.linux.system.repo.mcp.apt_mirantis.docker
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: bond0_ab_ovs_vxlan_mesh
        ens6:
          role: bond1_ab_ovs_floating

environment_metadata:
    public_gateway: 172.17.16.1
    public_cidr: 172.17.16.0/24
    public_allocation_start: 172.17.16.201
    public_allocation_end: 172.17.16.245
    tempest_test_target: gtw01*
