nodes:
  kvm01.mcp-offline-vxlan.local:
    reclass_storage_name: infra_kvm_node01
    roles:
    - infra_kvm
    - linux_system_codename_xenial
    # - features_offline_resolv
    # - features_offline_ntp
    # - features_vcp_gateway
    interfaces:
      one1:
        role: single_mgm
        # deploy_address: 10.10.0.241
        # deploy_network_netmask: 255.255.0.0
        # deploy_network_gateway: 10.10.0.1
      ten1:
        role: bond0_ab_nondvr_vxlan_ctl_mesh_raw
        # single_address: 10.11.0.241
        # tenant_address: 10.12.0.241
      ten2:
        role: bond0_ab_nondvr_vxlan_ctl_mesh_raw
        # single_address: 10.11.0.241
        # tenant_address: 10.12.0.241

  kvm02.mcp-offline-vxlan.local:
    reclass_storage_name: infra_kvm_node02
    roles:
    - infra_kvm
    - linux_system_codename_xenial
    # - features_offline_resolv
    # - features_offline_ntp
    # - features_vcp_gateway
    interfaces:
      one1:
        role: single_mgm
        # deploy_address: 10.10.0.242
        # deploy_network_netmask: 255.255.0.0
        # deploy_network_gateway: 10.10.0.1
      ten1:
        role: bond0_ab_nondvr_vxlan_ctl_mesh_raw
        # single_address: 10.11.0.242
        # tenant_address: 10.12.0.242
      ten2:
        role: bond0_ab_nondvr_vxlan_ctl_mesh_raw
        # single_address: 10.11.0.242
        # tenant_address: 10.12.0.242

  kvm03.mcp-offline-vxlan.local:
    reclass_storage_name: infra_kvm_node03
    roles:
    - infra_kvm
    - linux_system_codename_xenial
    # - features_offline_resolv
    # - features_offline_ntp
    # - features_vcp_gateway
    interfaces:
      one1:
        role: single_mgm
        # deploy_address: 10.10.0.243
        # deploy_network_netmask: 255.255.0.0
        # deploy_network_gateway: 10.10.0.1
      ten1:
        role: bond0_ab_nondvr_vxlan_ctl_mesh_raw
        # single_address: 10.11.0.243
        # tenant_address: 10.12.0.243
      ten2:
        role: bond0_ab_nondvr_vxlan_ctl_mesh_raw
        # single_address: 10.11.0.243
        # tenant_address: 10.12.0.243

  kvm04.mcp-offline-vxlan.local:
    reclass_storage_name: infra_kvm_node04
    roles:
    - infra_kvm_wo_gluster
    - linux_system_codename_xenial
    - salt_master_host
    # - features_offline_resolv
    # - features_offline_ntp
    # - features_vcp_gateway
    interfaces:
      one1:
        role: single_mgm
        # deploy_address: 10.10.0.244
        # deploy_network_netmask: 255.255.0.0
        # deploy_network_gateway: 10.10.0.1
      ten1:
        role: bond0_ab_nondvr_vxlan_ctl_mesh_raw
        # single_address: 10.11.0.244
        # tenant_address: 10.12.0.244
      ten2:
        role: bond0_ab_nondvr_vxlan_ctl_mesh_raw
        # single_address: 10.11.0.244
        # tenant_address: 10.12.0.244

  kvm05.mcp-offline-vxlan.local:
    reclass_storage_name: infra_kvm_node05
    roles:
    - infra_kvm_wo_gluster
    - linux_system_codename_xenial
    - salt_master_host
    # - features_offline_resolv
    # - features_offline_ntp
    # - features_vcp_gateway
    interfaces:
      one1:
        role: single_mgm
        # deploy_address: 10.10.0.245
        # deploy_network_netmask: 255.255.0.0
        # deploy_network_gateway: 10.10.0.1
      ten1:
        role: bond0_ab_nondvr_vxlan_ctl_mesh_raw
        # single_address: 10.11.0.245
        # tenant_address: 10.12.0.245
      ten2:
        role: bond0_ab_nondvr_vxlan_ctl_mesh_raw
        # single_address: 10.11.0.245
        # tenant_address: 10.12.0.245

  kvm06.mcp-offline-vxlan.local:
    reclass_storage_name: infra_kvm_node06
    roles:
    - infra_kvm_wo_gluster
    - linux_system_codename_xenial
    - salt_master_host
    # - features_offline_resolv
    # - features_offline_ntp
    # - features_vcp_gateway
    interfaces:
      one1:
        role: single_mgm
        # deploy_address: 10.10.0.246
        # deploy_network_netmask: 255.255.0.0
        # deploy_network_gateway: 10.10.0.1
      ten1:
        role: bond0_ab_nondvr_vxlan_ctl_mesh_raw
        # single_address: 10.11.0.246
        # tenant_address: 10.12.0.246
      ten2:
        role: bond0_ab_nondvr_vxlan_ctl_mesh_raw
        # single_address: 10.11.0.246
        # tenant_address: 10.12.0.246

  cmp<<count>>.mcp-offline-vxlan.local:
    reclass_storage_name: openstack_compute_rack01
    roles:
    - openstack_compute
    - linux_system_codename_xenial
    # - features_offline_resolv
    # - features_offline_ntp
    interfaces:
      one1:
        role: single_mgm
      ten1:
        role: bond0_ab_dvr_vxlan_ctl_mesh_floating
        # role: bond0_ab_dvr_vxlan_ctl_mesh_external_vlan
        # external_vlan: 1112
        # external_address: 10.16.0.224
        # external_network_netmask: 255.255.0.0
      ten2:
        role: bond0_ab_dvr_vxlan_ctl_mesh_floating
        # role: bond0_ab_dvr_vxlan_ctl_mesh_external_vlan
        # external_vlan: 1112

  osd<<count>>.mcp-offline-vxlan.local:
    reclass_storage_name: ceph_osd_rack01
    roles:
    - ceph_osd
    - linux_system_codename_xenial
    # - features_offline_resolv
    # - features_offline_ntp
    interfaces:
      one1:
        role: single_mgm
      ten1:
        role: bond0_ab_vlan_ceph_public_backend
      ten2:
        role: bond0_ab_vlan_ceph_public_backend

  gtw01.mcp-offline-vxlan.local:
    reclass_storage_name: openstack_gateway_node01
    roles:
    - openstack_gateway_octavia
    - linux_system_codename_xenial
    # - features_offline_resolv
    # - features_offline_ntp
    interfaces:
      one1:
        role: single_mgm
        # deploy_address: 10.10.0.224
        # deploy_network_netmask: 255.255.0.0
        # deploy_network_gateway: 10.10.0.1
      ten1:
        role: bond0_ab_dvr_vxlan_ctl_mesh_external_vlan
        # role: bond0_ab_dvr_vxlan_ctl_mesh_external
        # role: bond0_ab_dvr_vxlan_ctl_mesh_floating
        # single_address: 10.11.0.224
        # tenant_address: 10.12.0.224
        external_address: 10.16.0.224
        external_network_netmask: 255.255.0.0
        external_vlan: 2439
      ten2:
        role: bond0_ab_dvr_vxlan_ctl_mesh_external_vlan
        # role: bond0_ab_dvr_vxlan_ctl_mesh_external
        # role: bond0_ab_dvr_vxlan_ctl_mesh_floating
        # single_address: 10.11.0.224
        # tenant_address: 10.12.0.224
        external_address: 10.16.0.224
        external_network_netmask: 255.255.0.0
        external_vlan: 2439

  gtw02.mcp-offline-vxlan.local:
    reclass_storage_name: openstack_gateway_node02
    roles:
    - openstack_gateway
    - linux_system_codename_xenial
    # - features_offline_resolv
    # - features_offline_ntp
    interfaces:
      one1:
        role: single_mgm
        # deploy_address: 10.10.0.225
        # deploy_network_netmask: 255.255.0.0
        # deploy_network_gateway: 10.10.0.1
      ten1:
        role: bond0_ab_dvr_vxlan_ctl_mesh_external_vlan
        # role: bond0_ab_dvr_vxlan_ctl_mesh_floating
        # role: bond0_ab_dvr_vxlan_ctl_mesh_external
        # single_address: 10.11.0.225
        # tenant_address: 10.12.0.225
        external_address: 10.16.0.225
        external_network_netmask: 255.255.0.0
        external_vlan: 2439
      ten2:
        role: bond0_ab_dvr_vxlan_ctl_mesh_external_vlan
        # role: bond0_ab_dvr_vxlan_ctl_mesh_floating
        # role: bond0_ab_dvr_vxlan_ctl_mesh_external
        # single_address: 10.11.0.225
        # tenant_address: 10.12.0.225
        external_address: 10.16.0.225
        external_network_netmask: 255.255.0.0
        external_vlan: 2439

  gtw03.mcp-offline-vxlan.local:
    reclass_storage_name: openstack_gateway_node03
    roles:
    - openstack_gateway
    - linux_system_codename_xenial
    # - features_offline_resolv
    # - features_offline_ntp
    interfaces:
      one1:
        role: single_mgm
        # deploy_address: 10.10.0.226
        # deploy_network_netmask: 255.255.0.0
        # deploy_network_gateway: 10.10.0.1
      ten1:
        role: bond0_ab_dvr_vxlan_ctl_mesh_external_vlan
        # role: bond0_ab_dvr_vxlan_ctl_mesh_floating
        # role: bond0_ab_dvr_vxlan_ctl_mesh_external
        # single_address: 10.11.0.226
        # tenant_address: 10.12.0.226
        external_address: 10.16.0.226
        external_network_netmask: 255.255.0.0
        external_vlan: 2439
      ten2:
        role: bond0_ab_dvr_vxlan_ctl_mesh_external_vlan
        # role: bond0_ab_dvr_vxlan_ctl_mesh_floating
        # role: bond0_ab_dvr_vxlan_ctl_mesh_external
        # single_address: 10.11.0.226
        # tenant_address: 10.12.0.226
        external_address: 10.16.0.226
        external_network_netmask: 255.255.0.0
        external_vlan: 2439

#     cfg01.cookied-cicd-ovs-maas.local:
#       reclass_storage_name: infra_config_node01
#       roles:
#       - infra_config
#       - linux_system_codename_xenial
#       - features_runtest_cfg
#       interfaces:
#         ens3:
#           role: single_static_mgm
#         ens4:
#           role: single_static_ctl

#     # Physical nodes
#     kvm01.cookied-cicd-ovs-maas.local:
#       reclass_storage_name: infra_kvm_node01
#       roles:
#       - infra_kvm
#       - linux_system_codename_xenial
#       interfaces:
#         enp3s0f0:
#           role: single_mgm_dhcp
#         enp3s0f1:
#           role: bond0_ab_ovs_vlan_ctl

#     kvm02.cookied-cicd-ovs-maas.local:
#       reclass_storage_name: infra_kvm_node02
#       roles:
#       - infra_kvm
#       - linux_system_codename_xenial
#       interfaces:
#         enp3s0f0:
#           role: single_mgm_dhcp
#         enp3s0f1:
#           role: bond0_ab_ovs_vlan_ctl

#     kvm03.cookied-cicd-ovs-maas.local:
#       reclass_storage_name: infra_kvm_node03
#       roles:
#       - infra_kvm
#       - linux_system_codename_xenial
#       interfaces:
#         enp3s0f0:
#           role: single_mgm_dhcp
#         enp3s0f1:
#           role: bond0_ab_ovs_vlan_ctl

#     osd<<count>>:
#       reclass_storage_name: ceph_osd_rack01
#       roles:
#       - ceph_osd
#       - linux_system_codename_xenial
#       interfaces:
#         enp9s0f0:
#           role: single_dhcp
#         enp9s0f1:
#           role: single_vlan_ctl
# #          role: bond0_ab_vlan_ceph_storage_backend

#     cmp<<count>>:
#       reclass_storage_name: openstack_compute_rack01
#       roles:
#       - openstack_compute
#       - linux_system_codename_xenial
#       interfaces:
#         enp9s0f0:
#           role: single_mgm_dhcp
#         enp9s0f1:
#           role: bond0_ab_dvr_vxlan_ctl_mesh_floating

#     gtw01.cookied-cicd-ovs-maas.local:
#       reclass_storage_name: openstack_gateway_node01
#       roles:
#       - openstack_gateway
#       - linux_system_codename_xenial
#       interfaces:
#         enp3s0f0:
#           role: single_mgm_dhcp
#         enp3s0f1:
#           role: bond0_ab_dvr_vxlan_ctl_mesh_external
#           external_address: 172.17.42.5
#           external_network_netmask: 255.255.255.192

#     gtw02.cookied-cicd-ovs-maas.local:
#       reclass_storage_name: openstack_gateway_node02
#       roles:
#       - openstack_gateway
#       - linux_system_codename_xenial
#       interfaces:
#         enp3s0f0:
#           role: single_mgm_dhcp
#         enp3s0f1:
#           role: bond0_ab_dvr_vxlan_ctl_mesh_external
#           external_address: 172.17.42.6
#           external_network_netmask: 255.255.255.192

#     gtw03.cookied-cicd-ovs-maas.local:
#       reclass_storage_name: openstack_gateway_node03
#       roles:
#       - openstack_gateway
#       - linux_system_codename_xenial
#       interfaces:
#         enp2s0f0:
#           role: single_mgm_dhcp
#         enp2s0f1:
#           role: bond0_ab_dvr_vxlan_ctl_mesh_external
#           external_address: 172.17.42.7
#           external_network_netmask: 255.255.255.192
