nodes:
    ctl01.cookied-cicd-ovs-maas.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - openstack_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    ctl02.cookied-cicd-ovs-maas.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - openstack_control
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    ctl03.cookied-cicd-ovs-maas.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - openstack_control
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs01.cookied-cicd-ovs-maas.local:
      reclass_storage_name: openstack_database_node01
      roles:
      - openstack_database_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs02.cookied-cicd-ovs-maas.local:
      reclass_storage_name: openstack_database_node02
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs03.cookied-cicd-ovs-maas.local:
      reclass_storage_name: openstack_database_node03
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg01.cookied-cicd-ovs-maas.local:
      reclass_storage_name: openstack_message_queue_node01
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg02.cookied-cicd-ovs-maas.local:
      reclass_storage_name: openstack_message_queue_node02
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg03.cookied-cicd-ovs-maas.local:
      reclass_storage_name: openstack_message_queue_node03
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    prx01.cookied-cicd-ovs-maas.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    prx02.cookied-cicd-ovs-maas.local:
      reclass_storage_name: openstack_proxy_node02
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cid01.cookied-cicd-ovs-maas.local:
      reclass_storage_name: cicd_control_node01
      roles:
      - cicd_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cid02.cookied-cicd-ovs-maas.local:
      reclass_storage_name: cicd_control_node02
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cid03.cookied-cicd-ovs-maas.local:
      reclass_storage_name: cicd_control_node03
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mon01.cookied-cicd-ovs-maas.local:
      reclass_storage_name: stacklight_server_node01
      roles:
      - stacklightv2_server_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mon02.cookied-cicd-ovs-maas.local:
      reclass_storage_name: stacklight_server_node02
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mon03.cookied-cicd-ovs-maas.local:
      reclass_storage_name: stacklight_server_node03
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mtr01.cookied-cicd-ovs-maas.local:
      reclass_storage_name: stacklight_telemetry_node01
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mtr02.cookied-cicd-ovs-maas.local:
      reclass_storage_name: stacklight_telemetry_node02
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mtr03.cookied-cicd-ovs-maas.local:
      reclass_storage_name: stacklight_telemetry_node03
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    log01.cookied-cicd-ovs-maas.local:
      reclass_storage_name: stacklight_log_node01
      roles:
      - stacklight_log_leader_v2
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    log02.cookied-cicd-ovs-maas.local:
      reclass_storage_name: stacklight_log_node02
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    log03.cookied-cicd-ovs-maas.local:
      reclass_storage_name: stacklight_log_node03
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cmn01.cookied-cicd-ovs-maas.local:
      reclass_storage_name: ceph_mon_node01
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cmn02.cookied-cicd-ovs-maas.local:
      reclass_storage_name: ceph_mon_node02
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cmn03.cookied-cicd-ovs-maas.local:
      reclass_storage_name: ceph_mon_node03
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    rgw01.cookied-cicd-ovs-maas.local:
      reclass_storage_name: ceph_rgw_node01
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    rgw02.cookied-cicd-ovs-maas.local:
      reclass_storage_name: ceph_rgw_node02
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    rgw03.cookied-cicd-ovs-maas.local:
      reclass_storage_name: ceph_rgw_node03
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl
