nodes:
    cfg01.cookied-cicd-ovs-maas.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      - features_runtest_cfg
      interfaces:
        ens3:
          role: single_static_mgm
        ens4:
          role: single_static_ctl

    # Physical nodes
    kvm01.cookied-cicd-ovs-maas.local:
      reclass_storage_name: infra_kvm_node01
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp9s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_ovs_vlan_ctl

    kvm02.cookied-cicd-ovs-maas.local:
      reclass_storage_name: infra_kvm_node02
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp9s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_ovs_vlan_ctl

    kvm03.cookied-cicd-ovs-maas.local:
      reclass_storage_name: infra_kvm_node03
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp9s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_ovs_vlan_ctl

    kvm04.cookied-cicd-ovs-maas.local:
      reclass_storage_name: infra_kvm_node04
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp9s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_ovs_vlan_ctl

    kvm05.cookied-cicd-ovs-maas.local:
      reclass_storage_name: infra_kvm_node05
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp9s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_ovs_vlan_ctl

    kvm06.cookied-cicd-ovs-maas.local:
      reclass_storage_name: infra_kvm_node06
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp9s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_ovs_vlan_ctl

    osd<<count>>:
      reclass_storage_name: ceph_osd_rack01
      roles:
      - ceph_osd
      - linux_system_codename_xenial
      interfaces:
        enp9s0f0:
          role: single_mgm_dhcp
        enp9s0f1:
          role: single_vlan_ctl
#          role: bond0_ab_vlan_ceph_storage_backend

    cmp<<count>>:
      reclass_storage_name: openstack_compute_rack01
      roles:
      - openstack_compute
      - linux_system_codename_xenial
      interfaces:
        enp9s0f0:
          role: single_mgm_dhcp
        enp9s0f1:
          role: bond0_ab_dvr_vxlan_ctl_mesh_floating

    gtw01.cookied-cicd-ovs-maas.local:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        enp9s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_dvr_vxlan_ctl_mesh_external
          external_address: 172.17.42.5
          external_network_netmask: 255.255.255.192

    gtw02.cookied-cicd-ovs-maas.local:
      reclass_storage_name: openstack_gateway_node02
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        enp9s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_dvr_vxlan_ctl_mesh_external
          external_address: 172.17.42.6
          external_network_netmask: 255.255.255.192

    gtw03.cookied-cicd-ovs-maas.local:
      reclass_storage_name: openstack_gateway_node03
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        enp9s0f0:
          role: single_mgm_dhcp
        enp2s0f1:
          role: bond0_ab_dvr_vxlan_ctl_mesh_external
          external_address: 172.17.42.7
          external_network_netmask: 255.255.255.192
