nodes:
    # Virtual Control Plane nodes
    cid01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: cicd_control_node01
      interfaces:
        ens3:
          role: single_ctl

    cid02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: cicd_control_node02
      interfaces:
        ens3:
          role: single_ctl

    cid03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: cicd_control_node03
      interfaces:
        ens3:
          role: single_ctl 

    ctl01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: openstack_control_node01
      classes:
      - system.linux.system.repo.mcp.apt_mirantis.docker
      interfaces:
        ens3:
          role: single_ctl

    ctl02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: openstack_control_node02
      interfaces:
        ens3:
          role: single_ctl

    ctl03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: openstack_control_node03
      interfaces:
        ens3:
          role: single_ctl

    dbs01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: openstack_database_node01
      interfaces:
        ens3:
          role: single_ctl

    dbs02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: openstack_database_node02
      interfaces:
        ens3:
          role: single_ctl

    dbs03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: openstack_database_node03
      interfaces:
        ens3:
          role: single_ctl

    msg01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: openstack_message_queue_node01
      interfaces:
        ens3:
          role: single_ctl

    msg02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: openstack_message_queue_node02
      interfaces:
        ens3:
          role: single_ctl

    msg03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: openstack_message_queue_node03
      interfaces:
        ens3:
          role: single_ctl

    prx01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: openstack_proxy_node01
      interfaces:
        ens3:
          role: single_ctl

    prx02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: openstack_proxy_node02
      interfaces:
        ens3:
          role: single_ctl

    mon01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_server_node01
      interfaces:
        ens3:
          role: single_ctl

    mon02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_server_node02
      interfaces:
        ens3:
          role: single_ctl

    mon03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_server_node03
      interfaces:
        ens3:
          role: single_ctl

    nal01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: opencontrail_analytics_node01
      interfaces:
        ens3:
          role: single_ctl

    nal02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: opencontrail_analytics_node02
      interfaces:
        ens3:
          role: single_ctl

    nal03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: opencontrail_analytics_node03
      interfaces:
        ens3:
          role: single_ctl

    ntw01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: opencontrail_control_node01
      interfaces:
        ens3:
          role: single_ctl

    ntw02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: opencontrail_control_node02
      interfaces:
        ens3:
          role: single_ctl

    ntw03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: opencontrail_control_node03
      interfaces:
        ens3:
          role: single_ctl

    mtr01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_telemetry_node01
      interfaces:
        ens3:
          role: single_ctl

    mtr02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_telemetry_node02
      interfaces:
        ens3:
          role: single_ctl

    mtr03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_telemetry_node03
      interfaces:
        ens3:
          role: single_ctl

    log01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_log_node01
      interfaces:
        ens3:
          role: single_ctl

    log02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_log_node02
      interfaces:
        ens3:
          role: single_ctl

    log03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_log_node03
      interfaces:
        ens3:
          role: single_ctl

    cmn01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: ceph_mon_node01
      interfaces:
        ens3:
          role: single_ctl

    cmn02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: ceph_mon_node02
      interfaces:
        ens3:
          role: single_ctl

    cmn03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: ceph_mon_node03
      interfaces:
        ens3:
          role: single_ctl

    rgw01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: ceph_rgw_node01
      interfaces:
        ens3:
          role: single_ctl

    rgw02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: ceph_rgw_node02
      interfaces:
        ens3:
          role: single_ctl

    rgw03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: ceph_rgw_node03
      interfaces:
        ens3:
          role: single_ctl

#    bmk01.cookied-bm-mcp-ocata-contrail.local:
#      reclass_storage_name: openstack_benchmark_node01
#      roles:
#      - openstack_benchmark
#      - linux_system_codename_xenial
#      interfaces:
#        ens3:
#          role: single_ctl
