nodes:
    cfg01:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      classes:
      - environment.cookied-cicd-pike-dvr-ceph.override_ntp_virtual
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cid01:
      reclass_storage_name: cicd_control_node01
      roles:
      - cicd_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cid02:
      reclass_storage_name: cicd_control_node02
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cid03:
      reclass_storage_name: cicd_control_node03
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl01:
      reclass_storage_name: openstack_control_node01
      roles:
      - infra_kvm
      - openstack_control_leader
      - openstack_database_leader
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl02:
      reclass_storage_name: openstack_control_node02
      roles:
      - infra_kvm
      - openstack_control
      - openstack_database
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl03:
      reclass_storage_name: openstack_control_node03
      roles:
      - infra_kvm
      - openstack_control
      - openstack_database
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    prx01:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    # Generator-based computes. For compatibility only
    cmp<<count>>:
      reclass_storage_name: openstack_compute_rack01
      roles:
      - openstack_compute
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: bond0_ab_ovs_vxlan_mesh
        ens6:
          role: bond1_ab_ovs_floating

    gtw01:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      classes:
      - system.linux.system.repo.mcp.apt_mirantis.docker
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: bond0_ab_ovs_vxlan_mesh
        ens6:
          role: bond1_ab_ovs_floating

    osd<<count>>:
      reclass_storage_name: ceph_osd_rack01
      roles:
      - ceph_osd
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cmn01:
      reclass_storage_name: ceph_mon_node01
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cmn02:
      reclass_storage_name: ceph_mon_node02
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cmn03:
      reclass_storage_name: ceph_mon_node03
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    rgw01:
      reclass_storage_name: ceph_rgw_node01
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    rgw02:
      reclass_storage_name: ceph_rgw_node02
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    rgw03:
      reclass_storage_name: ceph_rgw_node03
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mdb01:
      reclass_storage_name: openstack_telemetry_node01
      roles:
      - linux_system_codename_xenial
      - openstack_telemetry
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mdb02:
      reclass_storage_name: openstack_telemetry_node02
      roles:
      - linux_system_codename_xenial
      - openstack_telemetry
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mdb03:
      reclass_storage_name: openstack_telemetry_node03
      roles:
      - linux_system_codename_xenial
      - openstack_telemetry
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

environment_metadata:
    public_gateway: 172.17.16.1
    public_cidr: 172.17.16.0/24
    public_allocation_start: 172.17.16.201
    public_allocation_end: 172.17.16.245
    tempest_test_target: gtw01*

