nodes:
    cfg01.sl-upgrade.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      - infra_maas
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    ctl01.sl-upgrade.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - openstack_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    ctl02.sl-upgrade.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - openstack_control
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    ctl03.sl-upgrade.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - openstack_control
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    dbs01.sl-upgrade.local:
      reclass_storage_name: openstack_database_node01
      roles:
      - openstack_database_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    dbs02.sl-upgrade.local:
      reclass_storage_name: openstack_database_node02
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    dbs03.sl-upgrade.local:
      reclass_storage_name: openstack_database_node03
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    msg01.sl-upgrade.local:
      reclass_storage_name: openstack_message_queue_node01
      roles:
      - infra_kvm
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    msg02.sl-upgrade.local:
      reclass_storage_name: openstack_message_queue_node02
      roles:
      - infra_kvm
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    msg03.sl-upgrade.local:
      reclass_storage_name: openstack_message_queue_node03
      roles:
      - infra_kvm
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    prx01.sl-upgrade.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    prx02.sl-upgrade.local:
      reclass_storage_name: openstack_proxy_node02
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mon01.sl-upgrade.local:
      reclass_storage_name: stacklight_monitor_node01
      roles:
      - stacklight_monitor_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mon02.sl-upgrade.local:
      reclass_storage_name: stacklight_monitor_node02
      roles:
      - stacklight_monitor
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mon03.sl-upgrade.local:
      reclass_storage_name: stacklight_monitor_node03
      roles:
      - stacklight_monitor
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mtr01.sl-upgrade.local:
      reclass_storage_name: stacklight_telemetry_node01
      roles:
      - stacklight_telemetry_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mtr02.sl-upgrade.local:
      reclass_storage_name: stacklight_telemetry_node02
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mtr03.sl-upgrade.local:
      reclass_storage_name: stacklight_telemetry_node03
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    log01.sl-upgrade.local:
      reclass_storage_name: stacklight_log_node01
      roles:
      - stacklight_log_leader_v1
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    log02.sl-upgrade.local:
      reclass_storage_name: stacklight_log_node02
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    log03.sl-upgrade.local:
      reclass_storage_name: stacklight_log_node03
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    # Generator-based computes. For compatibility only
    cmp<<count>>.sl-upgrade.local:
      reclass_storage_name: openstack_compute_rack01
      roles:
      - openstack_compute
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens5:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens6:
          role: bond1_ab_ovs_floating

    gtw01.sl-upgrade.local:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens5:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens6:
          role: bond1_ab_ovs_floating

#    gtw02.sl-upgrade.local:
#      reclass_storage_name: openstack_gateway_node02
#      roles:
#      - openstack_gateway
#      - linux_system_codename_xenial
#      interfaces:
#        ens3:
#          role: single_dhcp
#        ens4:
#          role: bond0_ab_ovs_vxlan_ctl_mesh
#        ens5:
#          role: bond0_ab_ovs_vxlan_ctl_mesh
#        ens6:
#          role: bond1_ab_ovs_floating
