nodes:
    ctl01.bm-mcp-dpdk-cicd-pipeline.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - openstack_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    ctl02.bm-mcp-dpdk-cicd-pipeline.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - openstack_control
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    ctl03.bm-mcp-dpdk-cicd-pipeline.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - openstack_control
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs01.bm-mcp-dpdk-cicd-pipeline.local:
      reclass_storage_name: openstack_database_node01
      roles:
      - openstack_database_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs02.bm-mcp-dpdk-cicd-pipeline.local:
      reclass_storage_name: openstack_database_node02
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs03.bm-mcp-dpdk-cicd-pipeline.local:
      reclass_storage_name: openstack_database_node03
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg01.bm-mcp-dpdk-cicd-pipeline.local:
      reclass_storage_name: openstack_message_queue_node01
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg02.bm-mcp-dpdk-cicd-pipeline.local:
      reclass_storage_name: openstack_message_queue_node02
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg03.bm-mcp-dpdk-cicd-pipeline.local:
      reclass_storage_name: openstack_message_queue_node03
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    prx01.bm-mcp-dpdk-cicd-pipeline.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    prx02.bm-mcp-dpdk-cicd-pipeline.local:
      reclass_storage_name: openstack_proxy_node02
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

#    mtr01.bm-mcp-dpdk-cicd-pipeline.local:
#      reclass_storage_name: stacklight_telemetry_node01
#      roles:
#      - stacklight_telemetry
#      - linux_system_codename_xenial
#      interfaces:
#        ens3:
#          role: single_ctl

#    mtr02.bm-mcp-dpdk-cicd-pipeline.local:
#      reclass_storage_name: stacklight_telemetry_node02
#      roles:
#      - stacklight_telemetry
#      - linux_system_codename_xenial
#      interfaces:
#        ens3:
#          role: single_ctl

#    mtr03.bm-mcp-dpdk-cicd-pipeline.local:
#      reclass_storage_name: stacklight_telemetry_node03
#      roles:
#      - stacklight_telemetry
#      - linux_system_codename_xenial
#      interfaces:
#        ens3:
#          role: single_ctl

    cid01.bm-mcp-dpdk-cicd-pipeline.local:
      reclass_storage_name: cicd_control_node01
      roles:
      - cicd_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    cid02.bm-mcp-dpdk-cicd-pipeline.local:
      reclass_storage_name: cicd_control_node02
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    cid03.bm-mcp-dpdk-cicd-pipeline.local:
      reclass_storage_name: cicd_control_node03
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl
