nodes:
    cfg01.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      - features_runtest_cfg
      interfaces:
        ens3:
          role: single_static_mgm
        ens4:
          role: single_static_ctl
    # Physical nodes

    kvm01.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: infra_kvm_node01
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp8s0f0:
          role: single_mgm_dhcp
        ens4f1:
          role: bond_ctl_contrail_lacp
        ens11f1:
          role: bond_ctl_contrail_lacp

    kvm02.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: infra_kvm_node02
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp8s0f0:
          role: single_mgm_dhcp
        ens4f1:
          role: bond_ctl_contrail_lacp
        ens11f1:
          role: bond_ctl_contrail_lacp

    kvm03.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: infra_kvm_node03
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp8s0f0:
          role: single_mgm_dhcp
        ens4f1:
          role: bond_ctl_contrail_lacp
        ens11f1:
          role: bond_ctl_contrail_lacp

    kvm04.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: infra_kvm_node04
      roles:
      - infra_kvm_wo_gluster
      - linux_system_codename_xenial
      - salt_master_host
      interfaces:
        enp8s0f0:
          role: single_mgm_dhcp
        ens4f1:
          role: bond_ctl_contrail_lacp
        ens11f1:
          role: bond_ctl_contrail_lacp

    kvm05.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: infra_kvm_node05
      roles:
      - infra_kvm_wo_gluster
      - linux_system_codename_xenial
      - salt_master_host
      interfaces:
        enp8s0f0:
          role: single_mgm_dhcp
        ens4f1:
          role: bond_ctl_contrail_lacp
        ens11f1:
          role: bond_ctl_contrail_lacp

    kvm06.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: infra_kvm_node06
      roles:
      - infra_kvm_wo_gluster
      - linux_system_codename_xenial
      - salt_master_host
      interfaces:
        enp8s0f0:
          role: single_mgm_dhcp
        ens4f1:
          role: bond_ctl_contrail_lacp
        ens11f1:
          role: bond_ctl_contrail_lacp

    osd<<count>>:
      reclass_storage_name: ceph_osd_rack01
      roles:
      - ceph_osd
      - linux_system_codename_xenial
      interfaces:
        eno1:
          role: single_dhcp
        ens1f1:
          role: bond_ctl_contrail_lacp
        ens2f1:
          role: bond_ctl_contrail_lacp
#          role: bond0_ab_vlan_ceph_storage_backend
# todo: add storage net for ceph to second lacp bond

    cmp<<count>>:
      reclass_storage_name: openstack_compute_rack01
      roles:
      - openstack_compute
      - linux_system_codename_xenial
      interfaces:
        eno1:
          role: single_dhcp
        ens1f0:
          role: bond_ctl_contrail_lacp
        ens1f1:
          role: bond_contrail_lacp
        ens2f0:
          role: bond_ctl_contrail_lacp
        ens2f1:
          role: bond_contrail_lacp

    cid01.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: cicd_control_node01
      roles:
      - cicd_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cid02.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: cicd_control_node02
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cid03.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: cicd_control_node03
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    ctl01.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - openstack_control_leader
      - linux_system_codename_xenial
      classes:
      - system.linux.system.repo.mcp.apt_mirantis.docker
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    ctl02.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - openstack_control
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    ctl03.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - openstack_control
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs01.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: openstack_database_node01
      roles:
      - openstack_database_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs02.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: openstack_database_node02
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs03.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: openstack_database_node03
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg01.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: openstack_message_queue_node01
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg02.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: openstack_message_queue_node02
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg03.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: openstack_message_queue_node03
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    prx01.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    prx02.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: openstack_proxy_node02
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mon01.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: stacklight_server_node01
      roles:
      - stacklightv2_server_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mon02.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: stacklight_server_node02
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mon03.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: stacklight_server_node03
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    nal01.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: opencontrail_analytics_node01
      roles:
      - opencontrail_analytics
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    nal02.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: opencontrail_analytics_node02
      roles:
      - opencontrail_analytics
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    nal03.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: opencontrail_analytics_node03
      roles:
      - opencontrail_analytics
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    ntw01.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: opencontrail_control_node01
      roles:
      - opencontrail_control
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    ntw02.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: opencontrail_control_node02
      roles:
      - opencontrail_control
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    ntw03.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: opencontrail_control_node03
      roles:
      - opencontrail_control
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mtr01.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: stacklight_telemetry_node01
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mtr02.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: stacklight_telemetry_node02
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mtr03.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: stacklight_telemetry_node03
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    log01.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: stacklight_log_node01
      roles:
      - stacklight_log_leader_v2
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    log02.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: stacklight_log_node02
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    log03.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: stacklight_log_node03
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cmn01.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: ceph_mon_node01
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cmn02.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: ceph_mon_node02
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cmn03.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: ceph_mon_node03
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    rgw01.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: ceph_rgw_node01
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    rgw02.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: ceph_rgw_node02
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    rgw03.heat-bm-cicd-queens-contrail-sl.local:
      reclass_storage_name: ceph_rgw_node03
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl
