nodes:
    ctl01.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - openstack_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    ctl02.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - openstack_control
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    ctl03.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - openstack_control
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs01.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_database_node01
      roles:
      - openstack_database_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs02.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_database_node02
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs03.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_database_node03
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg01.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_message_queue_node01
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg02.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_message_queue_node02
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg03.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_message_queue_node03
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    prx01.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    prx02.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_proxy_node02
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cid01.released-bm-pike-ovs.local:
      reclass_storage_name: cicd_control_node01
      roles:
      - cicd_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cid02.released-bm-pike-ovs.local:
      reclass_storage_name: cicd_control_node02
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cid03.released-bm-pike-ovs.local:
      reclass_storage_name: cicd_control_node03
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mon01.released-bm-pike-ovs.local:
      reclass_storage_name: stacklight_server_node01
      roles:
      - stacklightv2_server_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mon02.released-bm-pike-ovs.local:
      reclass_storage_name: stacklight_server_node02
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mon03.released-bm-pike-ovs.local:
      reclass_storage_name: stacklight_server_node03
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mtr01.released-bm-pike-ovs.local:
      reclass_storage_name: stacklight_telemetry_node01
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mtr02.released-bm-pike-ovs.local:
      reclass_storage_name: stacklight_telemetry_node02
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mtr03.released-bm-pike-ovs.local:
      reclass_storage_name: stacklight_telemetry_node03
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    log01.released-bm-pike-ovs.local:
      reclass_storage_name: stacklight_log_node01
      roles:
      - stacklight_log_leader_v2
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    log02.released-bm-pike-ovs.local:
      reclass_storage_name: stacklight_log_node02
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    log03.released-bm-pike-ovs.local:
      reclass_storage_name: stacklight_log_node03
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cmn01.released-bm-pike-ovs.local:
      reclass_storage_name: ceph_mon_node01
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cmn02.released-bm-pike-ovs.local:
      reclass_storage_name: ceph_mon_node02
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cmn03.released-bm-pike-ovs.local:
      reclass_storage_name: ceph_mon_node03
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    rgw01.released-bm-pike-ovs.local:
      reclass_storage_name: ceph_rgw_node01
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    rgw02.released-bm-pike-ovs.local:
      reclass_storage_name: ceph_rgw_node02
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    rgw03.released-bm-pike-ovs.local:
      reclass_storage_name: ceph_rgw_node03
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mdb01.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_telemetry_node01
      roles:
      - linux_system_codename_xenial
      - openstack_telemetry
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mdb02.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_telemetry_node02
      roles:
      - linux_system_codename_xenial
      - openstack_telemetry
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    mdb03.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_telemetry_node03
      roles:
      - linux_system_codename_xenial
      - openstack_telemetry
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dns01.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_dns_node01
      roles:
      - openstack_dns
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dns02.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_dns_node02
      roles:
      - openstack_dns
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    kmn01.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_barbican_node01
      roles:
      - openstack_barbican
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    kmn02.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_barbican_node02
      roles:
      - openstack_barbican
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    kmn03.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_barbican_node03
      roles:
      - openstack_barbican
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl
