nodes:
    cfg01.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl01.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - infra_kvm
      - openstack_control_leader
      - openstack_database_leader
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl02.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - infra_kvm
      - openstack_control
      - openstack_database
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl03.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - infra_kvm
      - openstack_control
      - openstack_database
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    prx01.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    # Generator-based computes. For compatibility only
    cmp<<count>>.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: openstack_compute_rack01
      roles:
      - openstack_compute
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: bond0_ab_ovs_vxlan_mesh
        ens6:
          role: bond1_ab_ovs_floating

    gtw01.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: bond0_ab_ovs_vxlan_mesh
        ens6:
          role: bond1_ab_ovs_floating

    osd1.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: ceph_osd_node1
      roles:
      - ceph_osd
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: single_storage

    osd2.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: ceph_osd_node2
      roles:
      - ceph_osd
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: single_storage

    cmn01.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: ceph_mon_node01
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: single_storage

    cmn02.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: ceph_mon_node02
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: single_storage

    cmn03.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: ceph_mon_node03
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: single_storage

    rgw01.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: ceph_rgw_node01
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: single_storage

    rgw02.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: ceph_rgw_node02
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: single_storage

    rgw03.mcp-dvr-ceph-rgw.local:
      reclass_storage_name: ceph_rgw_node03
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: single_storage