nodes:
    cfg01.cookied-mcp-mitaka-dvr-ceph.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl01.cookied-mcp-mitaka-dvr-ceph.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - infra_kvm
      - openstack_control_leader
      - openstack_database_leader
      - openstack_message_queue
      - features_designate_pool_manager_database
      - features_designate_pool_manager
      - features_designate_pool_manager_keystone
      - features_lvm_backend_control
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl02.cookied-mcp-mitaka-dvr-ceph.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - infra_kvm
      - openstack_control
      - openstack_database
      - openstack_message_queue
      - features_designate_pool_manager_database
      - features_designate_pool_manager
      - features_lvm_backend_control
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl03.cookied-mcp-mitaka-dvr-ceph.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - infra_kvm
      - openstack_control
      - openstack_database
      - openstack_message_queue
      - features_designate_pool_manager_database
      - features_designate_pool_manager
      - features_lvm_backend_control
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    prx01.cookied-mcp-mitaka-dvr-ceph.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - features_designate_pool_manager_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    osd<<count>>.cookied-mcp-mitaka-dvr-ceph.local:
      reclass_storage_name: ceph_osd_rack01
      roles:
      - ceph_osd
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mon01.cookied-mcp-mitaka-dvr-ceph.local:
      reclass_storage_name: stacklight_server_node01
      roles:
      - ceph_mon
      - stacklightv2_server_leader
      - stacklight_telemetry_leader
      - stacklight_log_leader_v2
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mon02.cookied-mcp-mitaka-dvr-ceph.local:
      reclass_storage_name: stacklight_server_node02
      roles:
      - ceph_mon
      - stacklightv2_server
      - stacklight_telemetry
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mon03.cookied-mcp-mitaka-dvr-ceph.local:
      reclass_storage_name: stacklight_server_node03
      roles:
      - ceph_mon
      - stacklightv2_server
      - stacklight_telemetry
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    # Generator-based computes. For compatibility only
    cmp<<count>>.cookied-mcp-mitaka-dvr-ceph.local:
      reclass_storage_name: openstack_compute_rack01
      roles:
      - openstack_compute
      - features_lvm_backend_volume_vdb
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: bond0_ab_ovs_vxlan_mesh
        ens6:
          role: bond1_ab_ovs_floating

    gtw01.cookied-mcp-mitaka-dvr-ceph.local:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: bond0_ab_ovs_vxlan_mesh
        ens6:
          role: bond1_ab_ovs_floating

    dns01.cookied-mcp-mitaka-dvr-ceph.local:
      reclass_storage_name: openstack_dns_node01
      roles:
      - features_designate_pool_manager_dns
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
          single_address: ${_param:openstack_dns_node01_address}

    dns02.cookied-mcp-mitaka-dvr-ceph.local:
      reclass_storage_name: openstack_dns_node02
      roles:
      - features_designate_pool_manager_dns
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
          single_address: ${_param:openstack_dns_node02_address}

    rgw01.cookied-mcp-pike-dvr-ceph.local:
      reclass_storage_name: ceph_rgw_node01
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    rgw02.cookied-mcp-pike-dvr-ceph.local:
      reclass_storage_name: ceph_rgw_node02
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    rgw03.cookied-mcp-pike-dvr-ceph.local:
      reclass_storage_name: ceph_rgw_node03
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
