nodes:
    cfg01.mcp11-ovs-dpdk.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl01.mcp11-ovs-dpdk.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - infra_kvm
      - openstack_control_leader
      - openstack_database_leader
      - openstack_message_queue
      - features_designate_bind9_database
      - features_designate_bind9
      - features_designate_bind9_keystone
      - features_designate_bind9_dns
      - features_lvm_backend_control
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl02.mcp11-ovs-dpdk.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - infra_kvm
      - openstack_control
      - openstack_database
      - openstack_message_queue
      - features_designate_bind9_database
      - features_designate_bind9
      - features_designate_bind9_dns
      - features_lvm_backend_control
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl03.mcp11-ovs-dpdk.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - infra_kvm
      - openstack_control
      - openstack_database
      - openstack_message_queue
      - features_designate_bind9_database
      - features_designate_bind9
      - features_lvm_backend_control
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    prx01.mcp11-ovs-dpdk.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - features_designate_bind9_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mon01.mcp11-ovs-dpdk.local:
      reclass_storage_name: stacklight_server_node01
      roles:
      - stacklightv2_server_leader
      - stacklight_telemetry_leader
      - stacklight_log_leader_v2
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mon02.mcp11-ovs-dpdk.local:
      reclass_storage_name: stacklight_server_node02
      roles:
      - stacklightv2_server
      - stacklight_telemetry
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mon03.mcp11-ovs-dpdk.local:
      reclass_storage_name: stacklight_server_node03
      roles:
      - stacklightv2_server
      - stacklight_telemetry
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    # Generator-based computes. For compatibility only
    cmp<<count>>.mcp11-ovs-dpdk.local:
      reclass_storage_name: openstack_compute_rack01
      roles:
      - openstack_compute
      - features_lvm_backend_volume_vdb
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: bond0_ab_ovs_vxlan_mesh
        ens6:
          role: bond1_ab_ovs_floating

    gtw01.mcp11-ovs-dpdk.local:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: bond0_ab_ovs_vxlan_mesh
        ens6:
          role: bond1_ab_ovs_floating

    osd<<count>>.mcp11-ovs-dpdk.local:
      reclass_storage_name: ceph_osd_rack01
      roles:
      - ceph_osd
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cmn01.mcp11-ovs-dpdk.local:
      reclass_storage_name: ceph_mon_node01
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cmn02.mcp11-ovs-dpdk.local:
      reclass_storage_name: ceph_mon_node02
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cmn03.mcp11-ovs-dpdk.local:
      reclass_storage_name: ceph_mon_node03
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    rgw01.mcp11-ovs-dpdk.local:
      reclass_storage_name: ceph_rgw_node01
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    rgw02.mcp11-ovs-dpdk.local:
      reclass_storage_name: ceph_rgw_node02
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    rgw03.cmcp11-ovs-dpdk.local:
      reclass_storage_name: ceph_rgw_node03
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl