nodes:
    cfg01.virtual-pike-ovs-dpdk.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl01.virtual-pike-ovs-dpdk.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - infra_kvm
      - openstack_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl02.virtual-pike-ovs-dpdk.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - infra_kvm
      - openstack_control
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl03.virtual-pike-ovs-dpdk.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - infra_kvm
      - openstack_control
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    dbs01.virtual-pike-ovs-dpdk.local:
      reclass_storage_name: openstack_database_node01
      roles:
      - openstack_database_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    dbs02.virtual-pike-ovs-dpdk.local:
      reclass_storage_name: openstack_database_node02
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    dbs03.virtual-pike-ovs-dpdk.local:
      reclass_storage_name: openstack_database_node03
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    msg01.virtual-pike-ovs-dpdk.local:
      reclass_storage_name: openstack_message_queue_node01
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    msg02.virtual-pike-ovs-dpdk.local:
      reclass_storage_name: openstack_message_queue_node02
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    msg03.virtual-pike-ovs-dpdk.local:
      reclass_storage_name: openstack_message_queue_node03
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    prx01.virtual-pike-ovs-dpdk.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - features_designate_bind9_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    # Generator-based computes. For compatibility only
    cmp<<count>>.virtual-pike-ovs-dpdk.local:
      reclass_storage_name: openstack_compute_rack01
      roles:
      - openstack_compute
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: bond0_ab_ovs_vxlan_mesh
        ens6:
          role: bond1_ab_ovs_floating

    gtw01.virtual-pike-ovs-dpdk.local:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: bond0_ab_ovs_vxlan_mesh
        ens6:
          role: bond1_ab_ovs_floating
