nodes:
    cfg01:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_static_mgm
        ens4:
          role: single_static_ctl

    cid01:
      reclass_storage_name: cicd_control_node01
      roles:
      - cicd_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cid02:
      reclass_storage_name: cicd_control_node02
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cid03:
      reclass_storage_name: cicd_control_node03
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl01:
      reclass_storage_name: kubernetes_control_node01
      roles:
      - kubernetes_control_contrail
      - linux_system_codename_xenial
      classes:
      - system.linux.system.repo.mcp.apt_mirantis.docker
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl02:
      reclass_storage_name: kubernetes_control_node02
      roles:
      - kubernetes_control_contrail
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl03:
      reclass_storage_name: kubernetes_control_node03
      roles:
      - kubernetes_control_contrail
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    prx01:
      reclass_storage_name: kubernetes_proxy_node01
      roles:
      - kubernetes_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    prx02:
      reclass_storage_name: kubernetes_proxy_node02
      roles:
      - kubernetes_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mon01:
      reclass_storage_name: stacklight_server_node01
      roles:
      - stacklightv2_server_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mon02:
      reclass_storage_name: stacklight_server_node02
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mon03:
      reclass_storage_name: stacklight_server_node03
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mtr01:
      reclass_storage_name: stacklight_telemetry_node01
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mtr02:
      reclass_storage_name: stacklight_telemetry_node02
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    mtr03:
      reclass_storage_name: stacklight_telemetry_node03
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    log01:
      reclass_storage_name: stacklight_log_node01
      roles:
      - stacklight_log_leader_v2
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    log02:
      reclass_storage_name: stacklight_log_node02
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    log03:
      reclass_storage_name: stacklight_log_node03
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    kvm01:
      reclass_storage_name: infra_kvm_node01
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    kvm02:
      reclass_storage_name: infra_kvm_node02
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    kvm03:
      reclass_storage_name: infra_kvm_node03
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cmn01:
      reclass_storage_name: ceph_mon_node01
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cmn02:
      reclass_storage_name: ceph_mon_node02
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cmn03:
      reclass_storage_name: ceph_mon_node03
      roles:
      - ceph_mon
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    rgw01:
      reclass_storage_name: ceph_rgw_node01
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    rgw02:
      reclass_storage_name: ceph_rgw_node02
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    rgw03:
      reclass_storage_name: ceph_rgw_node03
      roles:
      - ceph_rgw
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    osd<<count>>:
      reclass_storage_name: ceph_osd_rack01
      roles:
      - ceph_osd
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cmp<<count>>:
      reclass_storage_name: kubernetes_compute_rack01
      roles:
      - salt_master_host
      - kubernetes_compute
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens5:
          role: bond0_ab_contrail_single
        ens4:
          role: single_ctl
